version: '3.7'
services:
  mongo:
    image: mongo:latest
    container_name: mongoDatabase
    restart: always
    env_file:
      - .env
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGODB_DB: ${MONGO_DB}
      MONGODB_USER: ${MONGO_USER}
      MONGODB_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - 27017:27017
    networks:
      - mongodb-network
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - db-data:/data/db
  apiServer:
    image: node:18-alpine
    container_name: apiBackendServer
    restart: always
    env_file:
      - .env
    working_dir: /app
    environment:
      API_PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - mongodb-network
    command: sh -c "npm install && npm run start:dev"
    volumes:
      - ./:/app
volumes:
  db-data:
    driver: local

networks:
  mongodb-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: "172.21.0.0/16"