name: Run Unit Tests for frontend

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name